name: fztimeago
description: Frazile Time Ago provides duration of datetime from a given date & time.
version: 1.0.1
homepage: https://github.com/FrazileDevelopers/Fztimeago

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.24.4
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.3
  test_api: ^0.6.1

flutter:
  # assets:
  #   - images/
  # fonts:
  #   - family: Google
  #     fonts:
  #       - asset: fonts/google-Regular.ttf
  #       - asset: fonts/google-Italic.ttf
  #         style: italic
